### ISSUE TITLE
Is this a dupe with the one provided out of box from xstate?

### ISSUE THREAD

**Issue by coodoo** [carloslfu/use-machine#18]
See [the code here](https://github.com/davidkpiano/xstate/blob/master/packages/xstate-react/src/index.ts#L27-L46).

Just wondering what's the difference between the two? Thanks.

**Comment by carloslfu** [comment]
Hi @coodoo, XState recently added it, while this implementation is evolving since November of 2018 -> https://github.com/carloslfu/use-machine/commit/d96bf817f13ccb7d04b2dfbf3895c7d65323ce3f. Looking into `@xstate/react` and `use-machine`, both differ in the API. This package (`use-machine`) is intended to expose the whole XState instance and keep up the same API as [Machine](https://github.com/davidkpiano/xstate/blob/master/src/Machine.ts#L11), while `@xstate/react` exposes `current` state and `send()`. I thought in start using `@xstate/react` in my projects but in some use cases I found it useful to expose the XState instance, however, if it's not your case, `@xstate/react` is a good solution and I would recommend to use it. Also, I plan to support both syntaxes `const [current, send] = useMachine(...)` and `const service = useMachine(...)` that's what I think is the best solution.

**Comment by coodoo** [comment]
Understood, thanks for providing all the details! 👍👍
